<?php
/**
 * //                            _ooOoo_
 * //                           o8888888o
 * //                           88" . "88
 * //                           (| -_- |)
 * //                            O\ = /O
 * //                        ____/`---'\____
 * //                      .   ' \\| |// `.
 * //                       / \\||| : |||// \
 * //                     / _||||| -:- |||||- \
 * //                       | | \\\ - /// | |
 * //                     | \_| ''\---/'' | |
 * //                      \ .-\__ `-` ___/-. /
 * //                   ___`. .' /--.--\ `. . __
 * //                ."" '< `.___\_<|>_/___.' >'"".
 * //               | | : `- \`.;`\ _ /`;.`/ - ` : | |
 * //                 \ \ `-. \_ __\ /__ _/ .-` / /
 * //         ======`-.____`-.___\_____/___.-`____.-'======
 * //                            `=---='
 * //
 * //         .............................................
 * //                  佛祖保佑             永无BUG
 * DEC :
 * User: David Wang
 * Time: 2018/7/24 下午2:50
 */

namespace wallet\classes\model;

use wulaphp\db\Table;

class WalletWithdrawOrder extends Table {
	public function updateWd($id = 0, $data = []) {
		unset($data['id']);
		$where['id']         = $id;

		return $this->update($data, $where);
	}

	public function update($data = null, $con = null, $cb = null) {
		return parent::update($data, $con, $cb); // TODO: Change the autogenerated stub
	}

	public function create($data) {
		unset($data['id']);
		$data['create_time'] = time();
		$rst                 = $this->insert($data);
		if ($rst) {
			return $rst;
		}

		return false;
	}
}